# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


general:
  use_uvloop: true

functions:
  webpage_query:
    _type: webpage_query
    webpage_url: https://docs.smith.langchain.com
    description: "Search for information about LangSmith. For any questions about LangSmith, you must use this tool!"
    embedder_name: nv-embedqa-e5-v5
  current_datetime:
    _type: current_datetime

llms:
  nim_llama33-70b:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.6
    top_p: 0.95
    max_tokens: 1024
    base_url: https://nim.aire.nvidia.com/v1/
  openai_llm:
    _type: nim
    model_name: openai/gpt-oss-120b
    temperature: 0.7
    top_p: 0.95
    max_tokens: 1024
    base_url: https://gpt-oss-120b-v4-runai-flops-test.inference.b8721236.dgxcloud.ai/v1
  nim_llama33_trajectory_eval_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.0
    top_p: 1.0
    max_tokens: 1024
    base_url: https://nim.aire.nvidia.com/v1/
  nim_llama31-8b:
    _type: nim
    model_name: meta/llama-3.1-8b-instruct
    temperature: 0.3
    top_p: 0.95
    max_tokens: 1024
    base_url: https://nim.aire.nvidia.com/v1/

embedders:
  nv-embedqa-e5-v5:
    _type: nim
    model_name: nvidia/nv-embedqa-e5-v5

workflow:
  _type: react_agent
  tool_names: [webpage_query, current_datetime]
  llm_name: nim_llama33-70b
  verbose: true
  parse_agent_response_max_retries: 3

eval:
  general:
    output:
      dir: ./examples/sdg_workflow/data/eval_runs
      cleanup: true
    dataset:
      _type: jsonl
      file_path: ./examples/sdg_workflow/data/ndd_output/2025-08-29/nat_eval_dataset_a43b4799-3d55-463f-b828-f4f01be0a0a2.jsonl

  evaluators:
    trajectory_accuracy:
      _type: trajectory
      llm_name: nim_llama33_trajectory_eval_llm
